apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-tls
  namespace: monitoring
spec:
  secretName: monitoring-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: "prometheus.trebinje.online"
  dnsNames:
    - "prometheus.trebinje.online"
    - "alertmanager.trebinje.online"
    - "grafana.trebinje.online"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
