apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lke-monitor-grafana
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage-retain
